language: php
dist: trusty
sudo: false
php:
  - '7.2'

install:
  - composer update
script:
  - php vendor/bin/phpunit tests --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
